### ISSUE TITLE
Works great on Centos 7.

### ISSUE THREAD

**Issue by pvanthony** [coalfire/make-centos-bootstick#1]
Thank you for sharing this script. The script has really help me a lot. Saved a lot of time for me. Helped me learn about kickstart installation. Great!!!

The script works great within Centos 7 live Gnome. Tried on my desktop, Fedora 23, the script worked but some how could not boot up. Has an error stating the isolinux file is missing or corrupted.

Please take this as only a fyi.

Once again thank you for sharing the script.

**Comment by natemarks** [comment]
Thanks for this script!  Do you have a sample kickstart that works with it?  I'm struggling a little  to get the kickstart partitioning straight .

**Comment by nbirnel** [comment]
@natemarks I don't have a full one I am able to share, but here is a snippet that includes some partitioning:

    # Partition clearing information
    clearpart --all --initlabel --drives=sda
    # Disk partitioning information
    part /boot --fstype="ext2" --size=512 --fsoptions="nodev"
    part swap --fstype="swap" --size=2048
    part pv.01 --fstype="lvmpv" --size=1 --grow
    volgroup MainGroup pv.01
    logvol /  --fstype="xfs" --grow --size=6144 --name=rootvol --vgname=MainGroup
    logvol /opt  --fstype="xfs" --size=10240 --name=opt --vgname=MainGroup --fsoptions="nodev"
    logvol /var  --fstype="xfs" --size=6144 --name=var --vgname=MainGroup --fsoptions="nosuid,noexec,nodev"
    logvol /future --fstype="ext4" --size=4096 --name=future --vgname=MainGroup --fsoptions="nodev"


I am sure you can find other working ones out on the web.
